create table if not exists public.landing_link_clicks (
  id bigint generated by default as identity primary key,
  page_key text not null,
  link_key text not null,
  created_at timestamptz not null default now(),
  constraint landing_link_clicks_page_key_length check (char_length(page_key) between 1 and 80),
  constraint landing_link_clicks_link_key_length check (char_length(link_key) between 1 and 80)
);

create index if not exists landing_link_clicks_page_link_created_idx
  on public.landing_link_clicks (page_key, link_key, created_at desc);

alter table public.landing_link_clicks enable row level security;

revoke all on table public.landing_link_clicks from anon, authenticated;
grant select, insert on table public.landing_link_clicks to service_role;
grant usage, select on sequence public.landing_link_clicks_id_seq to service_role;

comment on table public.landing_link_clicks is
  'First-party, server-recorded click events for public landing pages. No personal data is stored.';
